### ISSUE TITLE
How to Generate the label png of pose

### ISSUE THREAD

**Issue by suenphey** [Engineering-Course/LIP_JPPNet#1]
Hi, I read your code but there is something not clear!
In the file "lip_reader.py" , line 186, pose_contents = tf.read_file(pose_id+'_{}.png'.format(i))
How to Generate the label png of pose？I guess from the code that every pose image has 16 pngs of labels, right?

**Comment by Engineering-Course** [comment]
Yes. We have updated a script to generate heatmaps.
