### ISSUE TITLE
Question about retrain your model

### ISSUE THREAD

**Issue by vonhathanh** [Engineering-Course/LIP_JPPNet#12]
Hi, I used your previous model here: https://github.com/Engineering-Course/LIP_SSL
Now I see that your new model has higher accuracy than the previous one so I want to replace it with this new model.  But the previous model output is 640x640 image and I want to train this new model to produce the same result(640x640). Can you help me figure out how to retrain your model so it can produce 640x640 images?

**Comment by Engineering-Course** [comment]
Yes, you can customize your input size during training or testing.
For inference, if your input size is fixed to 640*640, you need to resize the results to the original image size.

**Comment by vonhathanh** [comment]
Thanks @Engineering-Course , I'll give it a try :D
