### ISSUE TITLE
How to generate csv file for own dataset?

### ISSUE THREAD

**Issue by ZanePenn** [Engineering-Course/LIP_JPPNet#16]
Thanks a lot for your solid work! I am planning to train JPPNet on my own dataset, but I don't know how to generate csv file like lip_train_set.csv to create heatmaps. what's the meaning of each column? Is there any APIs I can use on my own dataset?

**Comment by Engineering-Course** [comment]
The README file in the package illustrates the format of the csv file. 
Actually, you can create your heatmaps directly without the need of generating such csv file.

**Comment by ZanePenn** [comment]
Thanks for your reply!
in the README.md you only tell us to 

> For LIP dataset, we have provided images, parsing labels, lists and the left-right flipping labels (labels_rev) for data augmentation. You need to generate the heatmaps of pose labels. We have provided a script for reference.

could you tell me more information in detail about how to generate? Thank you!

**Comment by ZanePenn** [comment]
Sorry, I didn't find any file or dir named Training Image Package, could you provide exact file name? Thank you!

**Comment by Engineering-Course** [comment]
TrainVal_pose_annotations.zip
![image](https://user-images.githubusercontent.com/7713394/43261756-71a7d422-9110-11e8-8362-188d6392cdaa.png)

**Comment by ZanePenn** [comment]
Thank you, it turns out that I ignored this dataset zip while I downloaded LIP, appreciate!

**Comment by M-Ghorbel** [comment]
@ZanePenn 
hello, did you succed to train your own dataset please? i didn't understand how to create the csv file
thank you
