### ISSUE TITLE
License

### ISSUE THREAD

**Issue by sberryman** [Engineering-Course/LIP_JPPNet#20]
What license is the code and model released under? I don't see anything on GitHub or your project page other than license terms for the LIP Dataset.

Thanks!

Edit:  🤞for MIT

**Comment by Engineering-Course** [comment]
Thanks.
It's MIT License and we have added.

**Comment by sberryman** [comment]
Thanks for the incredibly quick response! 

I'll be testing out your network on two security cameras (4k resolution) the next several weeks. The cameras cover a busy pedestrian boardwalk with over 2,000 unique pedestrians daily.
