### ISSUE TITLE
How to calculate IOUs?

### ISSUE THREAD

**Issue by h982639009** [Engineering-Course/LIP_JPPNet#24]
Could you please tell me how to calculate IOUs ?

**Comment by Engineering-Course** [comment]
See this [example](https://github.com/Engineering-Course/LIP_SSL/blob/master/test_human.py)

**Comment by h982639009** [comment]
Thanks for your reply. But I met some trouble when running the evaluation code.

when  exectuting this line of code in function **fast_hist**
           return np.bincount(n * a[k].astype(int) + b[k], minlength=n**2).reshape(n, n)
ValueError: total size of new array must be unchanged

It seems the results of np.bincount should be 20*20 for LIP, but I got 404 in my case.

result images and label images are both pixel-wise label in range(0,20).  Do you know what the problem is ?
