### ISSUE TITLE
Annotation for test set

### ISSUE THREAD

**Issue by xiaokaisq** [Engineering-Course/LIP_JPPNet#26]
Hello! Thank you very much for you great work. In  you LIP dataset, I find three sets, train, validation and test. But I am not able to find the parsing annotation for test set. Is that provided?

**Comment by Engineering-Course** [comment]
The annotation for the test set is withheld for benchmarking purposes.

**Comment by xiaokaisq** [comment]
I see. Thank you very much!

Clay Gong <notifications@github.com> 于2018年8月29日周三 下午5:59写道：
