### ISSUE TITLE
There is no upsample module?

### ISSUE THREAD

**Issue by zhly0** [Engineering-Course/LIP_JPPNet#33]
Hi,Engineering-Course：
Reading your code,I found that there is no upsample module in the human paring part,your input size is 384x384,and downsample the input all the way to 48x48,then 48x48 is the output size of the model,and we can resize the 48x48 output image to the size we want.Am I right?
Thanks.

**Comment by Engineering-Course** [comment]
Yes

**Comment by zhly0** [comment]
Thanks！
