### ISSUE TITLE
Using pose ground truth for training?

### ISSUE THREAD

**Issue by KeepGoing2019HaHa** [Engineering-Course/LIP_JPPNet#44]
Hi, I see that you are using pose ground truth during training, which is in create_heatmaps.py.
But in the paper, It said that 

> self-supervised human joints generated from our parsing results for different bodies

which means that pose ground truth should be generated from parsing results, but not huaman annotated labels.

So, is there something that I was missing?

**Comment by Engineering-Course** [comment]
JPPNet needs pose gt, while SS-JPPNet does not.
