### ISSUE TITLE
How to train the JPPNet by two phase?

### ISSUE THREAD

**Issue by Anikily** [Engineering-Course/LIP_JPPNet#49]
I have notice that :'We first train ResNet-101 on the human parsing task for 30 epochs using the pre-trained models and networks settings from [7]. Then, we train the joint framework end-to-end for another 30 epochs.'

But in the code there is only training joint framework 35 epochs.

**Comment by Engineering-Course** [comment]
Yes, and the code from [7] is also publicly available.

**Comment by Anikily** [comment]
@Engineering-Course ok,xiexieni
