### ISSUE TITLE
Freeze model

### ISSUE THREAD

**Issue by achalshah20** [Engineering-Course/LIP_JPPNet#5]
Hi, can you provide tensorflow frozen model? I can freeze model from checkpoint but I don't know what are the output nodes? 

My goal is to use your pretrained model in c++.

**Comment by Engineering-Course** [comment]
I think you can find the output nodes in the network and then freeze the model.
They are 'fc3_pose/conv6'  and 'fc3_parsing/parsing_human'.

**Comment by achalshah20** [comment]
Smal tensorflow question. How do you find these output nodes from checkpoint information?

**Comment by Engineering-Course** [comment]
@achalshah20  Look for the name scopes of layers or print the variables names.

**Comment by achalshah20** [comment]
Thanks. I figured it out. Tensorflow has newcheckpoint parser which was helpful.

**Comment by ElephantGit** [comment]
> Thanks. I figured it out. Tensorflow has newcheckpoint parser which was helpful.
Hi, Dear achalshah20, could you please share your method to freeze the model?
