### ISSUE TITLE
path

### ISSUE THREAD

**Issue by Jimooon** [Engineering-Course/LIP_JPPNet#9]
Hi! 
Your list/train_rev.txt shows the path to image, mask and mask_rev, and i can't find the right path from LIP datasets. 
![1](https://user-images.githubusercontent.com/38744917/40603781-822a5cfe-624c-11e8-9847-c81712574354.png)
images = []  TrainVal_images/train_images
masks = [] TrainVal_parsing_annotations/train_ssegmentations
masks_rev = [] ?
Is this right? and cannot find the third one?
thankyou~

**Comment by Jimooon** [comment]
Hi, Thank for reply.
i can't find this in datasets?
![1](https://user-images.githubusercontent.com/38744917/40608723-fdeb802a-625b-11e8-81fb-a56b4b2a5b7d.png)

**Comment by Jimooon** [comment]
Thankyou~~ i found it.

**Comment by Deicide-LC** [comment]
@Jimooon Excuse me , I want to know which dataset is labels

**Comment by 7oud** [comment]
@Jimooon In which folder? I have the same question and didn't find `train_rev.txt` file
